#include "cmb.h"
#include "cmb_utils.h"

// utils
int cmbSetup()
{
    return cdHere();
}
// commands
void cmbHelp()
{
	// TODO: The text needs to be fixed.
    printf("Usage: cmb <command> [options]\n"
           "`cmb` is a simple CLI tool for project management and build automation using CMake.\n\n"
           "Commands:\n"
           "  cmb new <projectName>\n"
           "      Create a new project in the current directory with the specified\n"
           "      <project_name>. This will automatically generate a few folders\n"
           "      and files. <project_name> is required.\n\n"

           "  cmb init [configName] [configsPath]\n"
           "      Generate CMake build files by reading the cmb_configs.json at\n"
           "      the specified <configsPath>. This step configures the generator,\n"
           "      compiler, and other settings based on the <configName>.\n"
           "      - If <kits_path> is omitted, the command will look for the file\n"
           "        in the current directory.\n"
           "      - If <kit_name> is omitted, the first entry in the JSON array\n"
           "        will be selected.\n\n"

           "  cmb build\n"
           "      Build the project using the build files generated by `cmb init`.\n"
           "      The output (e.g., executable files) will be placed in the\n"
           "      designated output directory.\n\n"

           "  cmb run\n"
           "      Run the output generated by `cmb build`.");
}
int cmbNew(char* argv[])
{
    if (argv[2] == NULL) {
        fprintf(stderr, "cmb: projectName is required for `cmb new`.\n");
        return 1;
    }

    // Create root dir
    if (makeRoot(argv[2]) == 1)
        return 1;

    // Create src/main.c
    FILE* file = NULL;
    if (writeMain(&file) == 1)
        return 1;

    // Create CMakeLists.txt
    file = NULL;
    if (writeCMakeLists(&file, argv[2]) == 1)
        return 1;

    // Create cmb_configs.json
    file = NULL;
    if (writeCmbConfigs(&file) == 1)
        return 1;

    return 0;
}
int cmbInit(int argc, char* argv[])
{
    const char* path = "cmb_configs.json";
    if (argv[2] != NULL)
        path = argv[2];
    
	FILE* file = NULL;
	ConfigsState state = openCmbConfigs(&file, path);

	if (state != CS_SUCCESS) {
		fprintf(stderr, "cmb: Failed to read cmb_configs.json");
		return 1;
	}

	readCmbConfigs(*file);

	return 0;
}
void cmbBuild(int argc, char* argv[])
{
    printf("cmb_build");
}
void cmbClean(int argc, char* argv[])
{
    printf("cmb_clean");
}
void cmbRun(int argc, char* argv[])
{
    printf("cmb_run");
}
