#include "cmb.h"
#include "cmb_utils.h"
#include <stdio.h>

// utils
int cmbSetup()
{
    return cdHere();
}
// commands
void cmbHelp()
{
	// TODO: The text needs to be fixed.
    printf("Usage: cmb <command> [options]\n"
           "`cmb` is a simple CLI tool for project management and build automation using CMake.\n\n"
           "Commands:\n"
           "  cmb init [configName] [configsPath]\n"
           "      Generate CMake build files by reading the cmb_configs.json at\n"
           "      the specified <configsPath>. This step configures the generator,\n"
           "      compiler, and other settings based on the <configName>.\n"
           "      - If <kits_path> is omitted, the command will look for the file\n"
           "        in the current directory.\n"
           "      - If <kit_name> is omitted, the first entry in the JSON array\n"
           "        will be selected.\n\n"

           "  cmb build\n"
           "      Build the project using the build files generated by `cmb init`.\n"
           "      The output (e.g., executable files) will be placed in the\n"
           "      designated output directory.\n\n"

           "  cmb run\n"
           "      Run the output generated by `cmb build`.");
}
int cmbInit(int argc, char* argv[])
{
    const char* path = "cmb_configs.json";
    if (argv[2] != NULL)
        path = argv[2];
	return 0;
}
void cmbBuild(int argc, char* argv[])
{
    printf("cmb_build");
}
void cmbClean(int argc, char* argv[])
{
    printf("cmb_clean");
}
void cmbRun(int argc, char* argv[])
{
    printf("cmb_run");
}
