#include "cmb.h"
#include "cmb_utils.h"
#include <stdio.h>

// commands
int cmb_help()
{
    printf("Usage: cmb <command> [options]\n"
           "`cmb` is a simple CLI tool for project management and build automation using CMake.\n\n"
           "Commands:\n"
           "  cmb init [preset_name]\n"
           "      Generate CMake build files by reading <preset_name> in ./cmb_presets.json.\n"
           "      - If [preset_name] is omitted, the first object in the JSON array\n"
           "        will be selected.\n\n"

           "  cmb build\n"
           "      Build the project using the build files generated by `cmb init`.\n"
           "      The output (e.g., executable files) will be placed in the\n"
           "      designated output directory.\n\n"

           "  cmb clean\n"
           "      Clean it dumb fuck.\n\n"

           "  cmb run\n"
           "      Run the output generated by `cmb build`.");
    return 0;
}
int cmb_init(int argc, char* argv[])
{
    Preset preset = { .source_dir = ".", .build_target = "Debug", .build_dir = "target" };

    int result = 0;
    if (argc >= 3) {
        result = get_preset("cmb_presets.json", argv[2], &preset);
    } else {
        result = get_preset("cmb_presets.json", NULL, &preset);
    }

    if (result != 0) {
        return result;
    }
    // printf("name: %s\n", preset.name);
    // printf("generator: %s\n", preset.generator);
    // printf("cCompiler: %s\n", preset.c_compiler);
    // printf("cppCompiler: %s\n", preset.cpp_compiler);
    // printf("source_dir: %s\n", preset.source_dir);
    // printf("build_target: %s\n", preset.build_target);
    // printf("build_dir: %s\n", preset.build_dir);

    run_command("cmake -S %s -B %s\\%s -G %s -DCMAKE_BUILD_TYPE=%s -DCMAKE_C_COMPILER=%s",
				preset.source_dir,
				preset.build_dir,
				preset.build_target,
				preset.generator,
				preset.build_target,
				preset.c_compiler);

    free_preset(&preset);

    return result;
}
int cmb_build(int argc, char* argv[])
{
    Preset preset = { .source_dir = ".", .build_target = "Debug", .build_dir = "target" };

    int result = 0;
    if (argc >= 3) {
        result = get_preset("cmb_presets.json", argv[2], &preset);
    } else {
        result = get_preset("cmb_presets.json", NULL, &preset);
    }

    if (result != 0) {
        return result;
    }

    run_command("cmake --build %s\\%s", preset.build_dir, preset.build_target);

    free_preset(&preset);

    return result;
}
int cmb_clean(int argc, char* argv[])
{
    printf("cmb_clean");
    return 0;
}
int cmb_run(int argc, char* argv[])
{
    Preset preset = { .source_dir = ".", .build_target = "Debug", .build_dir = "target" };

    int result = 0;
    if (argc >= 3) {
        result = get_preset("cmb_presets.json", argv[2], &preset);
    } else {
        result = get_preset("cmb_presets.json", NULL, &preset);
    }

    if (result != 0) {
        return result;
    }

    run_command("%s\\%s\\bin\\%s", preset.build_dir, preset.build_target, preset.run);

    free_preset(&preset);

    return result;
}
